# Generated by Django 5.0.7 on 2024-07-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='categories',
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='docs.document'),
        ),
    ]
