# Generated by Django 5.0.7 on 2024-07-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_remove_document_categories_document_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
